FROM node:20-alpine3.18

WORKDIR /app

COPY package*.json ./
RUN npm install

# accept NEXT_PUBLIC_MEDICATE_BASE_URL from build args
ARG NEXT_PUBLIC_MEDICATE_BASE_URL
ARG NEXT_PUBLIC_MEDICATE_SUPPORT_URL


ENV NEXT_PUBLIC_MEDICATE_BASE_URL=$NEXT_PUBLIC_MEDICATE_BASE_URL
ENV NEXT_PUBLIC_MEDICATE_SUPPORT_URL=$NEXT_PUBLIC_MEDICATE_SUPPORT_URL

COPY . .

# build with the injected env
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]


